[package]
edition.workspace = true
license.workspace = true
name = "gitana-git-http"
repository.workspace = true
rust-version.workspace = true
version = "0.1.0"

[lints]
workspace = true

[dependencies]
gitana-file-store.workspace = true
gitana-object.workspace = true
gitana-object-store.workspace = true
gitana-repository.workspace = true
gitana-trust.workspace = true
hmac.workspace = true
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
gitana-file-store-memory.workspace = true
serde_json.workspace = true
ssh-key = { workspace = true, features = ["ed25519"] }
tokio = { workspace = true, features = ["macros", "rt"] }
