[package]
description = "Git configuration file parser."
edition.workspace = true
license.workspace = true
name = "gitana-config"
repository.workspace = true
rust-version.workspace = true
version.workspace = true
[lints]
workspace = true

[dependencies]
thiserror.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
