[package]
edition.workspace = true
license.workspace = true
name = "gta-core"
repository.workspace = true
rust-version.workspace = true
version = "0.1.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
gitana-config.workspace = true
gitana-file-store.workspace = true
gitana-file-store-local.workspace = true
gitana-git-http.workspace = true
gitana-object.workspace = true
gitana-object-store.workspace = true
gitana-repository.workspace = true
gitana-worktree.workspace = true
reqwest.workspace = true
sha2.workspace = true

[dev-dependencies]
gitana-file-store-memory.workspace = true
ssh-key = { workspace = true, features = ["ed25519", "rand_core"] }
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
