//! Git object storage: read/write git objects by id over a [`FileStore`].
//!
//! Composition crate: it wires [`gitana_object`]'s codecs onto a
//! [`gitana_file_store::FileStore`] backend, scoped to one repository. Generic
//! over the backend `F` and the hash algorithm `H` — layers are wired with
//! compile-time generics (see docs/hlds/storage-layer.md). Reads try the loose object
//! first, then stored packfiles: an object is located through the pack's `.idx` (id →
//! offset) and decoded on demand from the compressed pack bytes, so no pack is decoded
//! in full to find (or miss) one object. Every loose read recomputes the id under `H`
//! and rejects a mismatch; objects served from a pack are content-addressed by
//! construction (`decode_object_at` computes each id from its bytes).

use std::cmp::Ordering;
use std::collections::{HashMap, HashSet};
use std::marker::PhantomData;
use std::sync::Arc;

use gitana_file_store::{FileStore, FileStoreError, WriteOutcome};

use gitana_object::{
	BitmapIndex, HashAlgorithm, MAX_OBJECT_SIZE, MidxEntry, MultiPackIndex, ObjectError, ObjectId,
	ObjectKind, PackEntry, PackIndex, PackedObject, apply_delta, build_reachability_bitmaps,
	decode_loose, decode_midx_bitmap, decode_multi_pack_index, decode_object_at, decode_pack_entry,
	decode_pack_index, encode_loose, encode_multi_pack_index,
	encode_multi_pack_index_with_reverse_index, encode_pack, encode_pack_index, loose_object_path,
	pack_index_entries, parse_commit, referenced_ids,
};
use tokio::sync::Mutex;

/// Re-exported so downstream layers name the parsed reachability bitmap through the store layer.
pub use gitana_object::BitmapIndex as ReachabilityBitmap;
/// Re-exported so downstream layers name object kinds through the store layer.
pub use gitana_object::ObjectKind as Kind;

const PACK_PREFIX: &str = "objects/pack/";
const PACK_SUFFIX: &str = ".pack";
const IDX_SUFFIX: &str = ".idx";
/// The multi-pack-index file, one index over every pack, regenerated by `repack`.
const MIDX_PATH: &str = "objects/pack/multi-pack-index";

/// Maximum stored packfile size (2 GiB).
pub const MAX_PACK_SIZE: u64 = 2 << 30;

/// Errors from object storage.
#[derive(Debug, thiserror::Error)]
pub enum ObjectStoreError {
	/// No object exists for the requested id.
	#[error("object not found")]
	NotFound,
	/// A stored object's recomputed id did not match the id it was read under.
	#[error("object corruption: stored under {requested}, content hashes to {actual}")]
	Corruption {
		/// The hex id the object was requested/stored under.
		requested: String,
		/// The hex id its bytes actually hash to.
		actual: String,
	},
	/// The underlying file store failed.
	#[error("file store error: {0}")]
	FileStore(#[from] FileStoreError),
	/// The object bytes could not be decoded.
	#[error("object decode error: {0}")]
	Object(#[from] ObjectError),
	/// A write exceeded the object (1 GiB) or pack (2 GiB) size limit.
	#[error("input exceeds the maximum size of {limit} bytes")]
	TooLarge {
		/// The limit that was exceeded.
		limit: u64,
	},
}

fn ensure_within(len: u64, limit: u64) -> Result<(), ObjectStoreError> {
	if len > limit {
		Err(ObjectStoreError::TooLarge { limit })
	} else {
		Ok(())
	}
}

/// The `.idx` sidecar path for a `.pack` path (`…/pack-<hex>.pack` → `…/pack-<hex>.idx`).
fn index_path(pack_path: &str) -> String {
	let stem = pack_path.strip_suffix(PACK_SUFFIX).unwrap_or(pack_path);
	format!("{stem}{IDX_SUFFIX}")
}

/// Order an object id against a lowercase-hex `prefix`: `Equal` when the id's hex rendering begins
/// with `prefix`, otherwise `Less`/`Greater` by the first differing nibble. Nibbles are compared
/// most-significant first, matching `ObjectId`'s byte-lexicographic `Ord`, so this drives a binary
/// search over an id-sorted slice. `prefix` must be lowercase hex (the caller validates it); a
/// non-hex char sorts as if greater than every nibble, which merely makes the prefix match nothing.
fn hex_prefix_cmp<H: HashAlgorithm>(id: &ObjectId<H>, prefix: &str) -> Ordering {
	let bytes = id.as_bytes();
	for (i, pc) in prefix.bytes().enumerate() {
		if i / 2 >= bytes.len() {
			// `prefix` is longer than a full id: the id is a proper prefix, so it sorts before.
			return Ordering::Less;
		}
		let Some(want) = (pc as char).to_digit(16) else {
			return Ordering::Less;
		};
		let byte = bytes[i / 2];
		let nibble = u32::from(if i % 2 == 0 { byte >> 4 } else { byte & 0x0f });
		match nibble.cmp(&want) {
			Ordering::Equal => {}
			other => return other,
		}
	}
	Ordering::Equal
}

/// The contiguous sub-slice of `sorted` (ascending by object id) whose ids' hex renderings begin
/// with `prefix`, located by two binary searches. `key` projects each element to its id. Both
/// `PackIndex::entries()` and `MultiPackIndex::object_ids()` are id-sorted, so this is `O(log n)`.
fn prefix_range<'a, H, T>(
	sorted: &'a [T],
	prefix: &str,
	key: impl Fn(&T) -> &ObjectId<H>,
) -> &'a [T]
where
	H: HashAlgorithm,
{
	let lo = sorted.partition_point(|e| hex_prefix_cmp(key(e), prefix).is_lt());
	let hi = sorted.partition_point(|e| !hex_prefix_cmp(key(e), prefix).is_gt());
	&sorted[lo..hi]
}

/// The order `encode_pack` writes object types in (commits, tags, trees, blobs). Used to sort
/// repack metadata so delta-friendly objects (same type, adjacent size) land in the same pack.
fn kind_rank(kind: ObjectKind) -> u8 {
	match kind {
		ObjectKind::Commit => 0,
		ObjectKind::Tag => 1,
		ObjectKind::Tree => 2,
		ObjectKind::Blob => 3,
	}
}

/// Cut sorted repack metadata into contiguous `[start, end)` ranges, each whose objects'
/// estimated packed size (uncompressed size + a small per-object header, a conservative upper
/// bound since compression only shrinks) stays under `max_pack_size` (less pack header/trailer
/// headroom). Every range holds at least one object, so a lone object larger than the budget gets
/// its own range (an object cannot span packs).
fn partition_ranges<H: HashAlgorithm>(
	meta: &[(ObjectId<H>, ObjectKind, u64)],
	max_pack_size: u64,
) -> Vec<(usize, usize)> {
	const PER_OBJECT_OVERHEAD: u64 = 32;
	const PACK_OVERHEAD: u64 = 128;
	let budget = max_pack_size.saturating_sub(PACK_OVERHEAD).max(1);

	let mut ranges = Vec::new();
	let mut start = 0;
	let mut acc = 0u64;
	for (i, entry) in meta.iter().enumerate() {
		let est = entry.2.saturating_add(PER_OBJECT_OVERHEAD);
		if i > start && acc.saturating_add(est) > budget {
			ranges.push((start, i));
			start = i;
			acc = 0;
		}
		acc = acc.saturating_add(est);
	}
	if start < meta.len() {
		ranges.push((start, meta.len()));
	}
	ranges
}

/// Git's geometric-repack split: given pack object-counts sorted ascending and a growth `factor`,
/// return how many of the smallest packs to roll up (the "batch"). The rest are kept untouched.
/// The batch is the largest prefix such that the kept packs form a geometric progression by count
/// (each ≥ `factor` × the total of everything smaller). `factor` is treated as ≥ 2; `f × x`
/// saturates rather than overflowing. `0` means the packs are already geometric.
fn geometric_split(counts_ascending: &[u64], factor: u64) -> usize {
	let factor = factor.max(2);
	let n = counts_ascending.len();
	if n == 0 {
		return 0;
	}
	// From the top, find where the progression first breaks going down.
	let mut split = n - 1;
	while split > 0 {
		if counts_ascending[split] < factor.saturating_mul(counts_ascending[split - 1]) {
			break;
		}
		split -= 1;
	}
	// Roll up everything below the break, then extend upward while the next pack does not itself
	// dominate the accumulated batch by `factor`.
	let mut total: u64 = counts_ascending[..split].iter().copied().sum();
	while split < n && counts_ascending[split] < factor.saturating_mul(total) {
		total = total.saturating_add(counts_ascending[split]);
		split += 1;
	}
	split
}

/// A pack's basename (`pack-<hex>.pack`) from its repository-relative path.
fn pack_basename(pack_path: &str) -> &str {
	pack_path.strip_prefix(PACK_PREFIX).unwrap_or(pack_path)
}

/// The name a MIDX records for a pack — its `.idx` basename (`pack-<hex>.idx`), as git does.
fn midx_pack_name(pack_path: &str) -> String {
	let base = pack_basename(pack_path);
	let stem = base.strip_suffix(PACK_SUFFIX).unwrap_or(base);
	format!("{stem}{IDX_SUFFIX}")
}

/// The `.pack` path for a MIDX pack name (`pack-<hex>.idx` → `objects/pack/pack-<hex>.pack`).
fn pack_path_from_midx_name(name: &str) -> String {
	let stem = name.strip_suffix(IDX_SUFFIX).unwrap_or(name);
	format!("{PACK_PREFIX}{stem}{PACK_SUFFIX}")
}

/// The `objects/pack/pack-<hex>.pack` path for a pack whose trailer checksum is `checksum`.
fn pack_path_for(checksum: &[u8]) -> String {
	format!("{PACK_PREFIX}pack-{}{PACK_SUFFIX}", hex(checksum))
}

/// The `objects/pack/multi-pack-index-<hex>.bitmap` path for a MIDX with the given checksum — git
/// names the reachability bitmap after the MIDX it belongs to.
fn midx_bitmap_path(midx_checksum: &[u8]) -> String {
	format!(
		"{PACK_PREFIX}multi-pack-index-{}.bitmap",
		hex(midx_checksum)
	)
}

/// Lowercase hex of `bytes`.
fn hex(bytes: &[u8]) -> String {
	let mut s = String::with_capacity(bytes.len() * 2);
	for byte in bytes {
		s.push_str(&format!("{byte:02x}"));
	}
	s
}

/// What a [`ObjectStore::repack`] / [`ObjectStore::repack_geometric`] consolidated: how many objects
/// were packed, into how many new packs, how many existing packs it left in place, and how many
/// now-redundant packs and loose objects it removed.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RepackReport {
	/// Objects written into the new pack(s).
	pub packed_objects: usize,
	/// New packs written (>1 when the object set exceeds the pack-size limit).
	pub packs_written: usize,
	/// Existing packs left untouched (>0 only for a geometric repack; 0 for a full repack).
	pub packs_kept: usize,
	/// Old packs deleted (each with its `.idx`).
	pub packs_removed: usize,
	/// Loose objects deleted.
	pub loose_removed: usize,
}

/// What [`ObjectStore::write_reachability_bitmap`] wrote: how many packs the multi-pack-index covers
/// and how many commits it bitmapped.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BitmapReport {
	/// Packs covered by the multi-pack-index the bitmap is built over.
	pub packs: usize,
	/// Commits given a reachability bitmap.
	pub bitmapped_commits: usize,
}

/// What a [`ObjectStore::prune_loose`] removed: the number of unreachable loose objects deleted.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PruneReport {
	/// Loose objects deleted (those absent from the caller's keep set).
	pub pruned: usize,
}

/// A pack's cached metadata: its parsed `.idx` (id → offset), the offsets sorted ascending (to
/// bound a single entry as `[offset, next_offset)` for a lazy range read), and its total byte
/// size. All `O(objects)` and small — never the pack's bytes.
struct PackMeta<H: HashAlgorithm> {
	index: PackIndex<H>,
	offsets_sorted: Vec<u64>,
	size: u64,
}

impl<H: HashAlgorithm> PackMeta<H> {
	/// The smallest entry offset strictly greater than `offset`, i.e. where the entry at `offset`
	/// ends. `None` for the last entry (its data runs to the pack body's end).
	fn next_offset_after(&self, offset: u64) -> Option<u64> {
		let i = self.offsets_sorted.partition_point(|&o| o <= offset);
		self.offsets_sorted.get(i).copied()
	}
}

/// The parse-once cache for the multi-pack-index: whether it has been loaded, and if so the
/// parsed index (or `None` when the file is absent or unreadable — treated as no MIDX).
enum MidxCache<H: HashAlgorithm> {
	Unloaded,
	Loaded(Option<Arc<MultiPackIndex<H>>>),
}

/// The parse-once cache for the current MIDX's reachability bitmap: whether it has been loaded, and
/// if so the parsed bitmap (or `None` when there is no bitmap, it is unreadable, or it does not
/// belong to the current MIDX — a stale bitmap is ignored). Invalidated whenever the MIDX is.
enum BitmapCache {
	Unloaded,
	Loaded(Option<Arc<BitmapIndex>>),
}

/// Git object storage layered over a file-store backend `F`, scoped to one repo, with
/// object ids under the hash algorithm `H`.
pub struct ObjectStore<F, H: HashAlgorithm> {
	files: F,
	/// Per-pack metadata (parsed `.idx`, sorted offsets, size) for locating an object without
	/// decoding the pack. Small; populated from the `.idx` sidecar on first touch of a pack.
	packs: Mutex<HashMap<String, Arc<PackMeta<H>>>>,
	/// Compressed pack bytes, read whole once and shared — the interactive read cache. Repack does
	/// not use it (it reads objects lazily via `read_path_range`), so consolidating a repository
	/// never holds a whole pack here.
	pack_bytes: Mutex<HashMap<String, Arc<Vec<u8>>>>,
	/// The parsed multi-pack-index, decoded on first lookup and invalidated by `repack`.
	midx: Mutex<MidxCache<H>>,
	/// The current MIDX's reachability bitmap, decoded on first lookup and invalidated whenever the
	/// MIDX is (a bitmap is bound to one MIDX by checksum).
	bitmap: Mutex<BitmapCache>,
	_hash: PhantomData<H>,
}

impl<F, H> ObjectStore<F, H>
where
	F: FileStore,
	H: HashAlgorithm,
{
	/// Build an object store over `files` for repository `repo`.
	pub fn new(files: F) -> Self {
		Self {
			files,
			packs: Mutex::new(HashMap::new()),
			pack_bytes: Mutex::new(HashMap::new()),
			midx: Mutex::new(MidxCache::Unloaded),
			bitmap: Mutex::new(BitmapCache::Unloaded),
			_hash: PhantomData,
		}
	}

	/// Borrow the underlying file store.
	pub fn file_store(&self) -> &F {
		&self.files
	}

	/// Write an object loose, returning its id. Idempotent: re-writing identical
	/// content is a no-op because the content-addressed path already exists.
	pub async fn write_object(
		&self,
		kind: ObjectKind,
		payload: &[u8],
	) -> Result<ObjectId<H>, ObjectStoreError> {
		ensure_within(payload.len() as u64, MAX_OBJECT_SIZE)?;
		let id = ObjectId::<H>::compute(kind, payload);
		let bytes = encode_loose(kind, payload);
		let path = loose_object_path(&id);
		match self.files.write_path_if_absent(&path, &bytes).await? {
			WriteOutcome::Written | WriteOutcome::AlreadyExists => Ok(id),
		}
	}

	/// Store a packfile under `objects/pack/`, keyed by its trailer checksum, alongside its
	/// `.idx` sidecar. Computing the index also validates the pack (a malformed or thin pack
	/// is rejected and never stored). Idempotent, and it writes a missing `.idx` even when the
	/// `.pack` is already present.
	///
	/// Takes the pack by value and **streams** both the pack and its `.idx` to the backend, so the
	/// write does not hold a second whole-pack copy (and a blob-store backend can multipart-upload
	/// rather than buffer the whole object).
	pub async fn write_pack(&self, pack: Vec<u8>) -> Result<(), ObjectStoreError> {
		ensure_within(pack.len() as u64, MAX_PACK_SIZE)?;
		// One decode both validates the pack and yields the `.idx` entries.
		let entries = pack_index_entries::<H>(&pack)?;
		let checksum = pack[pack.len() - H::RAW_LEN..].to_vec();
		let idx_bytes = encode_pack_index::<H>(&entries, &checksum)?;
		let pack_path = pack_path_for(&checksum);

		let pack_len = pack.len() as u64;
		self
			.files
			.write_path_stream_if_absent(&pack_path, Box::new(std::io::Cursor::new(pack)), pack_len)
			.await?;
		let idx_len = idx_bytes.len() as u64;
		self
			.files
			.write_path_stream_if_absent(
				&index_path(&pack_path),
				Box::new(std::io::Cursor::new(idx_bytes)),
				idx_len,
			)
			.await?;
		Ok(())
	}

	/// Read an object by id, from a loose object or a stored pack.
	pub async fn read_object(
		&self,
		id: &ObjectId<H>,
	) -> Result<(ObjectKind, Vec<u8>), ObjectStoreError> {
		match self.files.read_path(&loose_object_path(id)).await {
			Ok(bytes) => {
				let (kind, payload) = decode_loose(&bytes)?;
				let actual = ObjectId::<H>::compute(kind, &payload);
				if &actual != id {
					return Err(ObjectStoreError::Corruption {
						requested: id.to_hex(),
						actual: actual.to_hex(),
					});
				}
				Ok((kind, payload))
			}
			Err(FileStoreError::NotFound) => match self.locate(id).await? {
				Some((pack_path, meta, offset)) => {
					let bytes = self.pack_bytes(&pack_path).await?;
					let object = decode_object_at::<H>(&bytes, &meta.index, offset)?;
					// Content-address the result: a stale or corrupt `.idx` could point this id at
					// the wrong offset, so the object we materialised must actually hash to `id`
					// (the whole-pack decode this replaced was keyed by the recomputed id).
					if &object.id != id {
						return Err(ObjectStoreError::Corruption {
							requested: id.to_hex(),
							actual: object.id.to_hex(),
						});
					}
					Ok((object.kind, object.data))
				}
				None => Err(ObjectStoreError::NotFound),
			},
			Err(other) => Err(other.into()),
		}
	}

	/// Read an object by id **without caching whole packs** — the loose file, or a packed object
	/// materialised through per-entry range reads (`[offset, next_offset)`, resolving deltas by
	/// further range reads). Peak memory is one delta chain, not a pack, so repack stays bounded
	/// even when consolidating many large packs.
	async fn read_object_bounded(
		&self,
		id: &ObjectId<H>,
	) -> Result<(ObjectKind, Vec<u8>), ObjectStoreError> {
		match self.files.read_path(&loose_object_path(id)).await {
			Ok(bytes) => {
				let (kind, payload) = decode_loose(&bytes)?;
				let actual = ObjectId::<H>::compute(kind, &payload);
				if &actual != id {
					return Err(ObjectStoreError::Corruption {
						requested: id.to_hex(),
						actual: actual.to_hex(),
					});
				}
				Ok((kind, payload))
			}
			Err(FileStoreError::NotFound) => match self.locate(id).await? {
				Some((pack_path, meta, offset)) => {
					let (kind, data) = self.read_packed_lazy(&pack_path, &meta, offset).await?;
					let actual = ObjectId::<H>::compute(kind, &data);
					if &actual != id {
						return Err(ObjectStoreError::Corruption {
							requested: id.to_hex(),
							actual: actual.to_hex(),
						});
					}
					Ok((kind, data))
				}
				None => Err(ObjectStoreError::NotFound),
			},
			Err(other) => Err(other.into()),
		}
	}

	/// Materialise the object at byte `offset` in `pack_path` by reading only its entry (and its
	/// delta chain's entries) via `read_path_range`, never loading the whole pack. Mirrors
	/// [`gitana_object::decode_object_at`] but with range reads; the visited-offset set guards a
	/// REF-delta cycle.
	async fn read_packed_lazy(
		&self,
		pack_path: &str,
		meta: &PackMeta<H>,
		offset: u64,
	) -> Result<(ObjectKind, Vec<u8>), ObjectStoreError> {
		let body_end = meta
			.size
			.checked_sub(H::RAW_LEN as u64)
			.ok_or(ObjectError::MalformedPack)?;

		let mut deltas: Vec<Vec<u8>> = Vec::new();
		let mut visited: HashSet<u64> = HashSet::new();
		let mut cursor = offset;
		let (kind, mut data) = loop {
			if !visited.insert(cursor) {
				return Err(ObjectError::MalformedPack.into());
			}
			let end = meta.next_offset_after(cursor).unwrap_or(body_end);
			if cursor >= end {
				return Err(ObjectError::MalformedPack.into());
			}
			let entry = self
				.files
				.read_path_range(pack_path, cursor, end - cursor)
				.await?;
			match decode_pack_entry::<H>(&entry)? {
				PackEntry::Base { kind, data } => break (kind, data),
				PackEntry::OfsDelta { distance, delta } => {
					deltas.push(delta);
					cursor = cursor
						.checked_sub(distance)
						.ok_or(ObjectError::MalformedPack)?;
				}
				PackEntry::RefDelta { base, delta } => {
					deltas.push(delta);
					cursor = meta
						.index
						.offset_of(&base)
						.ok_or(ObjectError::UnresolvedDeltaBase)?;
				}
			}
		};
		for delta in deltas.iter().rev() {
			data = apply_delta(&data, delta)?;
		}
		Ok((kind, data))
	}

	/// Whether an object with `id` is stored, loose or packed.
	pub async fn exists_object(&self, id: &ObjectId<H>) -> Result<bool, ObjectStoreError> {
		if self.files.exists(&loose_object_path(id)).await? {
			return Ok(true);
		}
		Ok(self.locate(id).await?.is_some())
	}

	/// Find which stored pack holds `id`, returning the pack path, its cached metadata, and the
	/// object's byte offset. Consults the multi-pack-index first (one binary search across every
	/// covered pack), then only the packs the MIDX does not cover; with no usable MIDX it scans
	/// each pack's `.idx`. Either way it reads no `.pack` bytes.
	async fn locate(
		&self,
		id: &ObjectId<H>,
	) -> Result<Option<(String, Arc<PackMeta<H>>, u64)>, ObjectStoreError> {
		let pack_paths: Vec<String> = self
			.files
			.list_prefix(PACK_PREFIX)
			.await?
			.into_iter()
			.filter(|path| path.ends_with(PACK_SUFFIX))
			.collect();

		// A MIDX is usable only if every pack it names still exists (else it is stale — a pack it
		// points at was deleted — and we scan everything). Packs added after it (e.g. a later
		// fetch) are simply not covered and are scanned separately.
		if let Some(midx) = self.multi_pack_index().await? {
			// The MIDX names packs by their `.idx` basename (git's convention).
			let on_disk: HashSet<String> = pack_paths.iter().map(|p| midx_pack_name(p)).collect();
			let usable = midx.pack_names().iter().all(|name| on_disk.contains(name));
			if usable {
				if let Some((pack_index, offset)) = midx.lookup(id) {
					let pack_path = pack_path_from_midx_name(&midx.pack_names()[pack_index]);
					let meta = self.pack_meta(&pack_path).await?;
					return Ok(Some((pack_path, meta, offset)));
				}
				let covered: HashSet<&str> = midx.pack_names().iter().map(String::as_str).collect();
				for path in &pack_paths {
					if covered.contains(midx_pack_name(path).as_str()) {
						continue;
					}
					let meta = self.pack_meta(path).await?;
					if let Some(offset) = meta.index.offset_of(id) {
						return Ok(Some((path.clone(), meta, offset)));
					}
				}
				return Ok(None);
			}
		}

		for path in &pack_paths {
			let meta = self.pack_meta(path).await?;
			if let Some(offset) = meta.index.offset_of(id) {
				return Ok(Some((path.clone(), meta, offset)));
			}
		}
		Ok(None)
	}

	/// Every stored object id whose lowercase-hex rendering begins with `prefix`, across loose and
	/// packed objects, deduplicated and returned id-sorted. Used for abbreviated-id resolution: the
	/// caller decides unique/absent/ambiguous from the count. `prefix` must be lowercase hex (each
	/// char a hex digit) and is normally 4 or more chars; an object stored both loose and packed (or
	/// in overlapping packs) is reported once. Packed ids are gathered with the same MIDX-then-per-
	/// pack strategy `locate` uses — one binary-searched range over the multi-pack-index when it is
	/// usable, plus each pack it does not cover — so nothing is double-counted or missed.
	pub async fn find_by_prefix(&self, prefix: &str) -> Result<Vec<ObjectId<H>>, ObjectStoreError> {
		let mut matches: HashSet<ObjectId<H>> = HashSet::new();

		// Loose: the first two hex chars select one `objects/<aa>/` fan-out — scan just that. (A
		// prefix shorter than the fan-out would need every directory; not a real abbreviation.)
		if prefix.len() >= 2 {
			let (dir, rest) = prefix.split_at(2);
			for entry in self.files.list_prefix(&format!("objects/{dir}/")).await? {
				let name = entry.rsplit('/').next().unwrap_or_default();
				if name.starts_with(rest)
					&& let Ok(id) = ObjectId::<H>::from_hex(&format!("{dir}{name}"))
				{
					matches.insert(id);
				}
			}
		} else {
			for id in self.loose_object_ids().await? {
				if id.to_hex().starts_with(prefix) {
					matches.insert(id);
				}
			}
		}

		let pack_paths: Vec<String> = self
			.files
			.list_prefix(PACK_PREFIX)
			.await?
			.into_iter()
			.filter(|path| path.ends_with(PACK_SUFFIX))
			.collect();

		// Packs the MIDX covers are searched once through it; the rest scan their own `.idx`. A stale
		// MIDX (it names a pack that no longer exists) is ignored, so every pack is scanned below.
		let covered: HashSet<String> = match self.multi_pack_index().await? {
			Some(midx) => {
				let on_disk: HashSet<String> = pack_paths.iter().map(|p| midx_pack_name(p)).collect();
				if midx.pack_names().iter().all(|name| on_disk.contains(name)) {
					for id in prefix_range(midx.object_ids(), prefix, |id| id) {
						matches.insert(*id);
					}
					midx.pack_names().iter().cloned().collect()
				} else {
					HashSet::new()
				}
			}
			None => HashSet::new(),
		};

		for path in &pack_paths {
			if covered.contains(&midx_pack_name(path)) {
				continue;
			}
			let meta = self.pack_meta(path).await?;
			for entry in prefix_range(meta.index.entries(), prefix, |entry| &entry.id) {
				matches.insert(entry.id);
			}
		}

		let mut out: Vec<ObjectId<H>> = matches.into_iter().collect();
		out.sort_unstable();
		Ok(out)
	}

	/// The parsed multi-pack-index, decoded on first use and cached (invalidated by `repack`).
	/// A missing or unreadable MIDX caches as `None`, so callers fall back to per-pack scans.
	async fn multi_pack_index(&self) -> Result<Option<Arc<MultiPackIndex<H>>>, ObjectStoreError> {
		if let MidxCache::Loaded(midx) = &*self.midx.lock().await {
			return Ok(midx.clone());
		}
		let loaded = match self.files.read_path(MIDX_PATH).await {
			Ok(bytes) => decode_multi_pack_index::<H>(&bytes).ok().map(Arc::new),
			Err(FileStoreError::NotFound) => None,
			Err(other) => return Err(other.into()),
		};
		*self.midx.lock().await = MidxCache::Loaded(loaded.clone());
		Ok(loaded)
	}

	/// The multi-pack-index only if it is still *usable* — every pack it names is present on disk.
	/// A MIDX that points at a since-deleted pack is stale: [`Self::locate`] scans packs directly
	/// rather than trust it, so the reachability bitmap bound to that MIDX must not be trusted either.
	/// Re-checked per call (packs can be removed out-of-band), as `locate` does.
	async fn usable_multi_pack_index(
		&self,
	) -> Result<Option<Arc<MultiPackIndex<H>>>, ObjectStoreError> {
		let Some(midx) = self.multi_pack_index().await? else {
			return Ok(None);
		};
		let on_disk: HashSet<String> = self
			.files
			.list_prefix(PACK_PREFIX)
			.await?
			.into_iter()
			.filter(|path| path.ends_with(PACK_SUFFIX))
			.map(|path| midx_pack_name(&path))
			.collect();
		if midx.pack_names().iter().all(|name| on_disk.contains(name)) {
			Ok(Some(midx))
		} else {
			Ok(None)
		}
	}

	/// Invalidate the cached multi-pack-index and its reachability bitmap together — the bitmap is
	/// bound to one MIDX by checksum, so any change to the on-disk MIDX drops both; the next lookup
	/// reloads from disk.
	async fn invalidate_midx_caches(&self) {
		*self.midx.lock().await = MidxCache::Unloaded;
		*self.bitmap.lock().await = BitmapCache::Unloaded;
	}

	/// The reachability bitmap belonging to the current multi-pack-index, decoded on first use and
	/// cached (invalidated whenever the MIDX is). `None` when there is no MIDX, no `.bitmap`, the
	/// bitmap is malformed, or it does not belong to the current MIDX (checksum mismatch) — a bitmap
	/// is an optimization, so any of these falls back to walking rather than failing.
	async fn reachability_bitmap(&self) -> Result<Option<Arc<BitmapIndex>>, ObjectStoreError> {
		if let BitmapCache::Loaded(bitmap) = &*self.bitmap.lock().await {
			return Ok(bitmap.clone());
		}
		let loaded = self.load_reachability_bitmap().await?;
		*self.bitmap.lock().await = BitmapCache::Loaded(loaded.clone());
		Ok(loaded)
	}

	/// Read and validate the current MIDX's `.bitmap` from disk (no caching — see
	/// [`Self::reachability_bitmap`]). A missing/malformed/foreign bitmap is `None`.
	async fn load_reachability_bitmap(&self) -> Result<Option<Arc<BitmapIndex>>, ObjectStoreError> {
		let Some(midx) = self.multi_pack_index().await? else {
			return Ok(None);
		};
		let bytes = match self
			.files
			.read_path(&midx_bitmap_path(midx.checksum()))
			.await
		{
			Ok(bytes) => bytes,
			Err(FileStoreError::NotFound) => return Ok(None),
			Err(other) => return Err(other.into()),
		};
		// A malformed bitmap is treated as absent (fall back to walking), never a hard error — as the
		// MIDX itself is. Bind it to this MIDX by checksum so a stale file left over from a prior pack
		// set is never trusted.
		match decode_midx_bitmap::<H>(&bytes) {
			Ok(bitmap) if bitmap.midx_checksum() == midx.checksum() => Ok(Some(Arc::new(bitmap))),
			Ok(_) | Err(_) => Ok(None),
		}
	}

	/// The current MIDX's reachability bitmap paired with that MIDX, or `None` when no *usable* bitmap
	/// is present. Both are needed together to resolve a bitmap's set bits back to object ids. Gated on
	/// [`Self::usable_multi_pack_index`], so a stale MIDX (naming a deleted pack) yields no bitmap even
	/// though its checksum still matches the `.bitmap` on disk — matching what object lookup trusts.
	async fn bitmap_and_midx(
		&self,
	) -> Result<Option<(Arc<BitmapIndex>, Arc<MultiPackIndex<H>>)>, ObjectStoreError> {
		let Some(midx) = self.usable_multi_pack_index().await? else {
			return Ok(None);
		};
		// The bitmap load validated its checksum against this same (cached) MIDX; a torn concurrent
		// invalidation just yields `None` here and falls back to the walk rather than assume.
		match self.reachability_bitmap().await? {
			Some(bitmap) => Ok(Some((bitmap, midx))),
			None => Ok(None),
		}
	}

	/// Whether a *usable* reachability bitmap is available to accelerate object enumeration — one whose
	/// MIDX still names only packs present on disk (see [`Self::bitmap_and_midx`]).
	pub async fn has_reachability_bitmap(&self) -> Result<bool, ObjectStoreError> {
		Ok(self.bitmap_and_midx().await?.is_some())
	}

	/// The set of every object id reachable from `tips`, using the reachability bitmap to cover a
	/// bitmapped commit (and its whole closure — trees, blobs, and ancestors) in one step and walking
	/// the object graph only for the uncovered frontier. With no bitmap this is a plain closure walk,
	/// identical in result to the graph traversal it replaces.
	///
	/// When `strict`, a missing object reached from a tip is a connectivity error (the want side must
	/// be complete); otherwise a missing object is skipped (a peer may advertise `have`s the store
	/// lacks). A commit's parents and a tree's gitlink entries are followed via
	/// [`referenced_ids`] exactly as the walk does, so a repo without a bitmap enumerates the same set
	/// as one with a bitmap for every supported (non-submodule) history.
	pub async fn reachable_object_closure(
		&self,
		tips: &[ObjectId<H>],
		strict: bool,
	) -> Result<HashSet<ObjectId<H>>, ObjectStoreError> {
		let bitmap = self.bitmap_and_midx().await?;
		let mut closure: HashSet<ObjectId<H>> = HashSet::new();
		let mut stack: Vec<ObjectId<H>> = tips.to_vec();
		while let Some(id) = stack.pop() {
			if closure.contains(&id) {
				continue;
			}
			// A bitmapped commit's entire reachable closure is known — add it in bulk and do not
			// descend (the bitmap already accounts for its trees, blobs, and ancestors).
			if let Some((bitmap, midx)) = &bitmap {
				if let Some(ids) = bitmap.reachable_from(&id, midx) {
					closure.extend(ids);
					continue;
				}
			}
			// Otherwise read and walk it. A missing object is fatal only on the strict (want) side.
			let (kind, data) = match self.read_object(&id).await {
				Ok(object) => object,
				Err(ObjectStoreError::NotFound) if !strict => continue,
				Err(other) => return Err(other),
			};
			closure.insert(id);
			stack.extend(referenced_ids::<H>(kind, &data)?);
		}
		Ok(closure)
	}

	/// Whether any commit in `targets` is reachable from `source` (a commit), following commit→parent
	/// edges only — never reading a tree or blob. Each commit's *direct parents* are tested against
	/// `targets` before anything deeper, so a target a step or two away short-circuits at once (the
	/// common incremental-fetch case, where the client already has the tip's parent — even when the tip
	/// itself is bitmapped). A parent that is itself bitmapped answers for its whole ancestry with a
	/// single bit test per target — the target's position in its reachability bitmap — and is then
	/// pruned, so deep history is never walked commit-by-commit nor materialized. A missing or
	/// non-commit frontier node contributes nothing.
	///
	/// Follows every parent to the root, so it is only correct where there is no shallow boundary to
	/// stop at — callers restrict it to a non-shallow repo (which is also the only kind that has a
	/// bitmap). With no bitmap this degrades to a plain early-exit commit walk.
	pub async fn commit_reaches_any(
		&self,
		source: ObjectId<H>,
		targets: &HashSet<ObjectId<H>>,
	) -> Result<bool, ObjectStoreError> {
		if targets.contains(&source) {
			return Ok(true);
		}
		let bitmap = self.bitmap_and_midx().await?;
		// The single-bit path maps each target to a bitmap position via the MIDX reverse index. Without
		// one — a foreign/corrupt `.bitmap` over a MIDX that carries no RIDX — no position resolves, so a
		// bitmapped parent would prune on an empty target set and hide a deeper target. Treat such a
		// bitmap as absent and walk, exactly as the pre-bitmap path (and the resolve-to-id path) did.
		let bitmap = bitmap.filter(|(_, midx)| midx.reverse_index().is_some());
		// Map each target to its bitmap position once, so a bitmapped parent below answers membership
		// with an O(1) bit test rather than materializing its whole commit-ancestry. Only *commit*
		// targets present in the MIDX are kept: a set bit at a non-commit's position means that object is
		// reachable, not that a commit target is, so restricting to the commit type index preserves the
		// commit-only contract. A target absent from the MIDX has no position and can never be reached
		// from a bitmapped parent (whose full closure is packed into that MIDX), so dropping it is safe.
		let target_positions: Vec<u32> = match &bitmap {
			Some((bitmap, midx)) => targets
				.iter()
				.filter_map(|target| midx.bitmap_position(target))
				.filter(|&position| bitmap.type_bitmap(ObjectKind::Commit).get(position))
				.collect(),
			None => Vec::new(),
		};
		let mut seen: HashSet<ObjectId<H>> = HashSet::from([source]);
		let mut stack: Vec<ObjectId<H>> = vec![source];
		while let Some(id) = stack.pop() {
			// Read this commit for its parent edges. A missing commit (a peer may name one the store
			// lacks) or a non-commit contributes nothing.
			let parents = match self.read_object(&id).await {
				Ok((ObjectKind::Commit, data)) => parse_commit::<H>(&data)?.parents,
				Ok(_) | Err(ObjectStoreError::NotFound) => continue,
				Err(other) => return Err(other),
			};
			for parent in parents {
				// A parent that is a target ends it in one edge — the near-tip case, regardless of whether
				// `id` was bitmapped.
				if targets.contains(&parent) {
					return Ok(true);
				}
				if !seen.insert(parent) {
					continue;
				}
				// A bitmapped parent's reachability bitmap has a set bit at every position it reaches, so a
				// target is reachable exactly when its bit is set — test each and then prune (every commit
				// above this parent is within that reachability). Otherwise keep walking.
				let reachability = match &bitmap {
					Some((bitmap, midx)) => midx
						.object_position(&parent)
						.and_then(|lexical| bitmap.commit_reachability(lexical as u32)),
					None => None,
				};
				match reachability {
					Some(reachability) => {
						if target_positions
							.iter()
							.any(|&position| reachability.get(position))
						{
							return Ok(true);
						}
					}
					None => stack.push(parent),
				}
			}
		}
		Ok(false)
	}

	/// The cached metadata for one pack, built and cached on first use: its `.idx` (from the
	/// sidecar, or rebuilt by decoding the pack once if the sidecar is absent — read-only, so no
	/// sidecar is written on the read path), the offsets sorted ascending, and the pack size.
	async fn pack_meta(&self, pack_path: &str) -> Result<Arc<PackMeta<H>>, ObjectStoreError> {
		if let Some(meta) = self.packs.lock().await.get(pack_path) {
			return Ok(Arc::clone(meta));
		}
		let index = match self.files.read_path(&index_path(pack_path)).await {
			Ok(bytes) => decode_pack_index::<H>(&bytes)?,
			Err(FileStoreError::NotFound) => {
				let pack = self.files.read_path(pack_path).await?;
				let entries = pack_index_entries::<H>(&pack)?;
				let checksum = pack[pack.len() - H::RAW_LEN..].to_vec();
				PackIndex::from_entries(entries, checksum)?
			}
			Err(other) => return Err(other.into()),
		};
		let mut offsets_sorted: Vec<u64> = index.entries().iter().map(|e| e.offset).collect();
		offsets_sorted.sort_unstable();
		let size = self.files.size(pack_path).await?;
		let meta = Arc::new(PackMeta {
			index,
			offsets_sorted,
			size,
		});
		self
			.packs
			.lock()
			.await
			.insert(pack_path.to_owned(), Arc::clone(&meta));
		Ok(meta)
	}

	/// The compressed bytes of one pack, read whole once and cached for on-demand object decode.
	async fn pack_bytes(&self, pack_path: &str) -> Result<Arc<Vec<u8>>, ObjectStoreError> {
		if let Some(bytes) = self.pack_bytes.lock().await.get(pack_path) {
			return Ok(Arc::clone(bytes));
		}
		let bytes = Arc::new(self.files.read_path(pack_path).await?);
		self
			.pack_bytes
			.lock()
			.await
			.insert(pack_path.to_owned(), Arc::clone(&bytes));
		Ok(bytes)
	}

	/// Consolidate storage: gather every loose object and every object in every existing pack
	/// into one or more new packs — each at most `max_pack_size` bytes — then delete the now
	/// redundant loose objects and old packs. No object is dropped; this changes only how objects
	/// are stored, not which exist (pruning unreachable objects is a separate concern). Returns
	/// `None` when nothing needs doing (already a single indexed pack with no loose objects).
	///
	/// **Memory-bounded:** the repo's content is never held all at once. Pass 1 reads each object
	/// once to record only its `(kind, size)` (dropping the data) and sorts that small metadata
	/// to group delta-friendly objects; the sorted list is cut into size-bounded partitions.
	/// Pass 2 then materialises, encodes, writes, and drops **one partition at a time**, so peak
	/// memory is ≈ one pack (≤ `max_pack_size`) plus `O(objects)` of metadata — independent of
	/// repo size. New packs are written before anything is deleted, so an object is never
	/// momentarily unreferenced on disk; a crash mid-way leaves redundant-but-correct storage a
	/// re-run cleans up. `max_pack_size` is clamped to [`MAX_PACK_SIZE`] (the absolute per-pack
	/// ceiling `write_pack` enforces).
	pub async fn repack(&self, max_pack_size: u64) -> Result<Option<RepackReport>, ObjectStoreError> {
		let max_pack_size = max_pack_size.min(MAX_PACK_SIZE);

		// Snapshot the packs to consolidate before writing the new ones.
		let old_packs: Vec<String> = self
			.files
			.list_prefix(PACK_PREFIX)
			.await?
			.into_iter()
			.filter(|path| path.ends_with(PACK_SUFFIX))
			.collect();
		let loose_ids = self.loose_object_ids().await?;

		// No-op only when the layout is already what repack would cheaply produce: nothing loose
		// and at most one pack that is indexed and within the limit. Multiple packs always re-pack
		// so repack can *consolidate* them into fewer (its original purpose); that is idempotent
		// when they are already optimally split. A lone pack lacking its `.idx` (unreadable by
		// stock git) or over `max_pack_size` (must be split) also re-packs.
		let noop = loose_ids.is_empty()
			&& match old_packs.as_slice() {
				[] => true,
				[only] => {
					self.files.exists(&index_path(only)).await?
						&& self.files.size(only).await? <= max_pack_size
				}
				_ => false,
			};
		if noop {
			return Ok(None);
		}

		Ok(Some(
			self
				.repack_batch(&old_packs, &[], &loose_ids, max_pack_size)
				.await?,
		))
	}

	/// Incrementally repack: keep the large packs and roll only the small packs — chosen by git's
	/// geometric split with growth `factor` — plus every loose object into new size-bounded packs,
	/// regenerating the multi-pack-index. Far cheaper than a full [`Self::repack`]: the kept packs'
	/// object *data* is never read (only every pack's `.idx`, needed to rebuild the MIDX). Returns
	/// `None` when nothing needs doing (packs already geometric and nothing loose).
	pub async fn repack_geometric(
		&self,
		max_pack_size: u64,
		factor: u64,
	) -> Result<Option<RepackReport>, ObjectStoreError> {
		let max_pack_size = max_pack_size.min(MAX_PACK_SIZE);
		let pack_paths: Vec<String> = self
			.files
			.list_prefix(PACK_PREFIX)
			.await?
			.into_iter()
			.filter(|path| path.ends_with(PACK_SUFFIX))
			.collect();
		let loose_ids = self.loose_object_ids().await?;

		// Order packs by object count (the geometric weight), smallest first, and pick the split.
		// The loose objects join as a virtual smallest pack: git packs them first and then splits
		// over the result, so their weight has to count when deciding whether the smallest real pack
		// still dominates — otherwise `gc` beside an already-geometric layout writes a fresh pack that
		// leaves the whole set non-geometric. The loose pseudo-pack (`None`) is always rolled in.
		let mut by_count: Vec<(u64, Option<String>)> = Vec::with_capacity(pack_paths.len() + 1);
		for path in pack_paths {
			let count = self.pack_meta(&path).await?.index.entries().len() as u64;
			by_count.push((count, Some(path)));
		}
		if !loose_ids.is_empty() {
			by_count.push((loose_ids.len() as u64, None));
		}
		by_count.sort_by(|a, b| a.0.cmp(&b.0).then_with(|| a.1.cmp(&b.1)));
		let counts: Vec<u64> = by_count.iter().map(|(count, _)| *count).collect();
		let split = geometric_split(&counts, factor);

		let mut batch: Vec<String> = Vec::new();
		let mut kept: Vec<String> = Vec::new();
		for (i, (_, item)) in by_count.iter().enumerate() {
			let Some(path) = item else { continue };
			if i < split {
				batch.push(path.clone());
			} else if self.files.exists(&index_path(path)).await? {
				kept.push(path.clone());
			} else {
				// A kept pack must have its `.idx` sidecar on disk — stock git needs it even with a
				// MIDX, and `pack_meta` only rebuilds a missing one in memory. Roll any such pack into
				// the batch instead, so the rewrite regenerates its sidecar (as a full repack would).
				batch.push(path.clone());
			}
		}
		if batch.is_empty() && loose_ids.is_empty() {
			// The packs are already geometric and nothing is loose, so no repack is due. The
			// maintenance command still owes a correct multi-pack-index, though: rebuild it when the
			// on-disk MIDX is absent or does not name exactly the current packs (a foreign tool wrote
			// the packs, or one was removed out-of-band). When it already matches, this is a true
			// no-op — lookups stay on the fast MIDX path either way.
			let want: HashSet<String> = kept.iter().map(|p| midx_pack_name(p)).collect();
			let fresh = match self.multi_pack_index().await? {
				Some(midx) => midx.pack_names().iter().cloned().collect::<HashSet<_>>() == want,
				None => kept.len() < 2,
			};
			if !fresh {
				self
					.write_or_clear_midx(&kept.iter().cloned().collect())
					.await?;
				self.invalidate_midx_caches().await;
			}
			return Ok(None);
		}
		Ok(Some(
			self
				.repack_batch(&batch, &kept, &loose_ids, max_pack_size)
				.await?,
		))
	}

	/// Rewrite the objects of `batch_packs` (plus `loose_ids`) into new size-bounded packs, delete
	/// those batch packs and the loose objects, and regenerate the multi-pack-index over
	/// `kept_packs` (left untouched) together with the new packs. Shared by [`Self::repack`] (batch
	/// = every pack, kept = none) and [`Self::repack_geometric`] (batch = the small packs).
	///
	/// **Memory-bounded**, as documented on [`Self::repack`]: pass 1 records each batch object's
	/// `(kind, size)` and drops the data; pass 2 encodes/writes/drops one size-bounded partition at
	/// a time, so peak memory is ≈ one pack plus `O(objects)` metadata — the kept packs are never
	/// read.
	async fn repack_batch(
		&self,
		batch_packs: &[String],
		kept_packs: &[String],
		loose_ids: &[ObjectId<H>],
		max_pack_size: u64,
	) -> Result<RepackReport, ObjectStoreError> {
		// Union of the batch's ids: each batch pack's index entries plus the loose objects.
		let mut ids: HashSet<ObjectId<H>> = HashSet::new();
		for path in batch_packs {
			for entry in self.pack_meta(path).await?.index.entries() {
				ids.insert(entry.id);
			}
		}
		ids.extend(loose_ids.iter().copied());

		// Pass 1: read each object once for its (kind, size), dropping the data. Sort like
		// `encode_pack` orders objects (type, then largest-first, then id) so a contiguous run
		// groups delta-friendly objects into one size-bounded partition. Reads are memory-bounded.
		let mut meta: Vec<(ObjectId<H>, ObjectKind, u64)> = Vec::with_capacity(ids.len());
		for id in &ids {
			let (kind, data) = self.read_object_bounded(id).await?;
			meta.push((*id, kind, data.len() as u64));
		}
		meta.sort_by(|a, b| {
			kind_rank(a.1)
				.cmp(&kind_rank(b.1))
				.then(b.2.cmp(&a.2))
				.then(a.0.cmp(&b.0))
		});

		// Pass 2: encode, write, and drop one partition at a time.
		let mut new_pack_paths: HashSet<String> = HashSet::new();
		for (start, end) in partition_ranges(&meta, max_pack_size) {
			let mut objects: Vec<PackedObject<H>> = Vec::with_capacity(end - start);
			for (id, _, _) in &meta[start..end] {
				let (kind, data) = self.read_object_bounded(id).await?;
				objects.push(PackedObject {
					id: *id,
					kind,
					data,
				});
			}
			self
				.encode_write_bounded(&objects, max_pack_size, &mut new_pack_paths)
				.await?;
		}

		// Delete the batch packs (except any a re-encode reproduced) and every loose object.
		let mut packs_removed = 0;
		for path in batch_packs {
			if new_pack_paths.contains(path) {
				continue;
			}
			self.files.delete_path(path, None).await?;
			self.files.delete_path(&index_path(path), None).await?;
			packs_removed += 1;
		}
		for id in loose_ids {
			self.files.delete_path(&loose_object_path(id), None).await?;
		}

		// Regenerate the MIDX over the kept packs plus the new ones (or drop it below two packs),
		// before invalidating the caches.
		let mut all_packs: HashSet<String> = kept_packs.iter().cloned().collect();
		all_packs.extend(new_pack_paths.iter().cloned());
		self.write_or_clear_midx(&all_packs).await?;

		// The caches may name deleted packs (and the MIDX changed); drop them (reads reload lazily).
		self.packs.lock().await.clear();
		self.pack_bytes.lock().await.clear();
		self.invalidate_midx_caches().await;

		Ok(RepackReport {
			packed_objects: meta.len(),
			packs_written: new_pack_paths.len(),
			packs_kept: kept_packs.len(),
			packs_removed,
			loose_removed: loose_ids.len(),
		})
	}

	/// Write the multi-pack-index covering `pack_paths` (≥ 2 packs), or delete any existing one
	/// when fewer (a lone pack needs no MIDX). Objects an id maps to are read from each pack's
	/// cached `.idx`; the pack id is the pack's rank in ASCII-sorted basename order.
	///
	/// This writes a *plain* MIDX (no reverse index), so any existing reachability bitmap is now
	/// bound to a stale MIDX and is removed — [`Self::write_reachability_bitmap`] rewrites both
	/// together when a bitmap is wanted.
	async fn write_or_clear_midx(
		&self,
		pack_paths: &HashSet<String>,
	) -> Result<(), ObjectStoreError> {
		if pack_paths.len() < 2 {
			match self.files.delete_path(MIDX_PATH, None).await {
				Ok(_) | Err(FileStoreError::NotFound) => return self.clear_midx_bitmaps().await,
				Err(other) => return Err(other.into()),
			}
		}

		let mut names: Vec<String> = pack_paths.iter().map(|path| midx_pack_name(path)).collect();
		names.sort();
		let name_to_id: HashMap<&str, u32> = names
			.iter()
			.enumerate()
			.map(|(i, name)| (name.as_str(), i as u32))
			.collect();

		let mut entries: Vec<MidxEntry<H>> = Vec::new();
		for path in pack_paths {
			let pack_id = name_to_id[midx_pack_name(path).as_str()];
			for entry in self.pack_meta(path).await?.index.entries() {
				entries.push(MidxEntry {
					id: entry.id,
					pack_id,
					offset: entry.offset,
				});
			}
		}
		let bytes = encode_multi_pack_index::<H>(&names, &entries)?;
		self.overwrite_path(MIDX_PATH, &bytes).await?;
		self.clear_midx_bitmaps().await
	}

	/// Delete every `multi-pack-index-*.bitmap` — each is named for (and only usable with) a specific
	/// MIDX, so a MIDX rewrite without a fresh matching bitmap must not leave one behind. A stock-git
	/// single-pack `pack-<hash>.bitmap` is a different, unrelated artifact and is left untouched.
	async fn clear_midx_bitmaps(&self) -> Result<(), ObjectStoreError> {
		for path in self.files.list_prefix(PACK_PREFIX).await? {
			let name = path.strip_prefix(PACK_PREFIX).unwrap_or(&path);
			if name.starts_with("multi-pack-index-") && name.ends_with(".bitmap") {
				match self.files.delete_path(&path, None).await {
					Ok(_) | Err(FileStoreError::NotFound) => {}
					Err(other) => return Err(other.into()),
				}
			}
		}
		Ok(())
	}

	/// Write a reverse-index-carrying multi-pack-index over the current packs plus a reachability
	/// `.bitmap` that bitmaps `selected_commits` (typically the ref tips). Git reads the result to
	/// answer reachability without walking history.
	///
	/// The largest pack (by object count) is preferred — it leads the bitmap object order, as git
	/// does. Any stale `multi-pack-index-*.bitmap` is removed first, so exactly one bitmap remains.
	/// Returns `None` when there are no packs to index. Reads every object once to classify it and to
	/// walk commit/tree reachability (blob bodies are never held), so peak memory is the non-blob
	/// object set plus one bitmap per selected commit as it is built.
	pub async fn write_reachability_bitmap(
		&self,
		selected_commits: &[ObjectId<H>],
	) -> Result<Option<BitmapReport>, ObjectStoreError> {
		let pack_paths: Vec<String> = self
			.files
			.list_prefix(PACK_PREFIX)
			.await?
			.into_iter()
			.filter(|path| path.ends_with(PACK_SUFFIX))
			.collect();
		if pack_paths.is_empty() {
			return Ok(None);
		}

		// MIDX pack ids are the rank of each pack's `.idx` basename in ASCII order (git's convention).
		let mut names: Vec<String> = pack_paths.iter().map(|path| midx_pack_name(path)).collect();
		names.sort();
		let name_to_id: HashMap<&str, u32> = names
			.iter()
			.enumerate()
			.map(|(i, name)| (name.as_str(), i as u32))
			.collect();

		// Gather every object's (pack, offset), and pick the largest pack to prefer in the order.
		let mut entries: Vec<MidxEntry<H>> = Vec::new();
		let mut preferred: (u32, usize) = (0, 0);
		for path in &pack_paths {
			let pack_id = name_to_id[midx_pack_name(path).as_str()];
			let meta = self.pack_meta(path).await?;
			if meta.index.entries().len() > preferred.1 {
				preferred = (pack_id, meta.index.entries().len());
			}
			for entry in meta.index.entries() {
				entries.push(MidxEntry {
					id: entry.id,
					pack_id,
					offset: entry.offset,
				});
			}
		}

		// Write the MIDX with its reverse index, then invalidate the cache and re-read it back to
		// drive the builder (it needs the reverse index, object order, and checksum).
		let midx_bytes =
			encode_multi_pack_index_with_reverse_index::<H>(&names, &entries, preferred.0)?;
		self.overwrite_path(MIDX_PATH, &midx_bytes).await?;
		self.invalidate_midx_caches().await;
		let midx = decode_multi_pack_index::<H>(&midx_bytes)?;

		// Pre-read objects into sync maps for the builder: every object's kind (for the type indexes
		// and to skip blob bodies) and every non-blob's bytes (to follow reachability).
		let mut kinds: HashMap<ObjectId<H>, ObjectKind> = HashMap::with_capacity(midx.len());
		let mut data: HashMap<ObjectId<H>, Vec<u8>> = HashMap::new();
		for id in midx.object_ids() {
			let (kind, bytes) = self.read_object_bounded(id).await?;
			if kind != ObjectKind::Blob {
				data.insert(*id, bytes);
			}
			kinds.insert(*id, kind);
		}

		// Only packed *commits* can be bitmapped: a caller may pass ref tips that are tag objects or
		// still-loose commits — `kinds` holds a kind only for objects in this MIDX, so this keeps just
		// the packed commits among the selection (the rest are covered by a later maintenance run).
		let selected: Vec<ObjectId<H>> = selected_commits
			.iter()
			.copied()
			.filter(|id| kinds.get(id) == Some(&ObjectKind::Commit))
			.collect();
		let built = build_reachability_bitmaps(
			&midx,
			&selected,
			|id| kinds.get(id).copied(),
			|id| data.get(id).cloned(),
		)?;
		let bitmap_bytes = built.encode::<H>(midx.checksum())?;

		// Publish only if the on-disk MIDX is still the one we built for. A concurrent maintenance
		// task could have rewritten it; then this bitmap's checksum-name would mismatch the MIDX and
		// readers would ignore it, so leave the other writer's state intact and report nothing done.
		let raw = H::RAW_LEN;
		match self.files.read_path(MIDX_PATH).await {
			Ok(on_disk) if on_disk.len() >= raw && on_disk[on_disk.len() - raw..] == *midx.checksum() => {
			}
			Ok(_) | Err(FileStoreError::NotFound) => return Ok(None),
			Err(other) => return Err(other.into()),
		}

		// One bitmap belongs to a MIDX; drop any stale ones, then overwrite the fresh checksum-named
		// file (a CAS loop, so a concurrent writer's bytes never masquerade as this call's).
		self.clear_midx_bitmaps().await?;
		self
			.overwrite_path(&midx_bitmap_path(midx.checksum()), &bitmap_bytes)
			.await?;
		// Drop the (necessarily empty) cached bitmap so the next reader loads the one just written.
		*self.bitmap.lock().await = BitmapCache::Unloaded;

		Ok(Some(BitmapReport {
			packs: pack_paths.len(),
			bitmapped_commits: built.commits().len(),
		}))
	}

	/// Overwrite `path` with `bytes`, retrying on a concurrent write (read-version → CAS). Used for
	/// the multi-pack-index and its reachability bitmap.
	async fn overwrite_path(&self, path: &str, bytes: &[u8]) -> Result<(), ObjectStoreError> {
		loop {
			let expected = match self.files.read_path_versioned(path).await {
				Ok((_, version)) => Some(version),
				Err(FileStoreError::NotFound) => None,
				Err(other) => return Err(other.into()),
			};
			match self
				.files
				.write_path_cas(path, bytes, expected.as_ref())
				.await
			{
				Ok(_) => return Ok(()),
				Err(FileStoreError::VersionMismatch) => continue,
				Err(other) => return Err(other.into()),
			}
		}
	}

	/// Encode `objects` into a pack and write it (with its `.idx`), recording its path in `out`.
	/// If the encoded pack exceeds `max_pack_size` and holds more than one object (an
	/// incompressible-data / zlib-overhead edge that the size-based partition under-estimated),
	/// split the range in half and recurse — so every written pack is ≤ `max_pack_size` unless it
	/// holds a single object whose packed form alone exceeds it (an object cannot span packs).
	async fn encode_write_bounded(
		&self,
		objects: &[PackedObject<H>],
		max_pack_size: u64,
		out: &mut HashSet<String>,
	) -> Result<(), ObjectStoreError> {
		let pack = encode_pack(objects);
		if pack.len() as u64 > max_pack_size && objects.len() > 1 {
			let mid = objects.len() / 2;
			Box::pin(self.encode_write_bounded(&objects[..mid], max_pack_size, out)).await?;
			Box::pin(self.encode_write_bounded(&objects[mid..], max_pack_size, out)).await?;
			return Ok(());
		}
		let path = pack_path_for(&pack[pack.len() - H::RAW_LEN..]);
		self.write_pack(pack).await?;
		out.insert(path);
		Ok(())
	}

	/// Every loose object id on disk, by scanning the `objects/<aa>/<rest>` fan-out (skipping
	/// the `pack`/`info` directories and any non-hex names).
	async fn loose_object_ids(&self) -> Result<Vec<ObjectId<H>>, ObjectStoreError> {
		let hex_len = H::RAW_LEN * 2;
		let mut ids = Vec::new();
		for dir in self.files.list_prefix("objects/").await? {
			let name = dir.rsplit('/').next().unwrap_or_default();
			if name.len() != 2 || !name.bytes().all(|b| b.is_ascii_hexdigit()) {
				continue;
			}
			for entry in self.files.list_prefix(&format!("{dir}/")).await? {
				let rest = entry.rsplit('/').next().unwrap_or_default();
				if rest.len() != hex_len - 2 || !rest.bytes().all(|b| b.is_ascii_hexdigit()) {
					continue;
				}
				if let Ok(id) = ObjectId::<H>::from_hex(&format!("{name}{rest}")) {
					ids.push(id);
				}
			}
		}
		Ok(ids)
	}

	/// Delete every loose object whose id is **not** in `keep`. `keep` is the caller's set of
	/// reachable object ids (see the prune safety rules); anything loose and absent from it is
	/// unreferenced and removed. Packed objects are never touched — only loose deletion. The
	/// caller is responsible for computing a complete `keep` set; there is no time-based grace,
	/// so a loose object written concurrently after `keep` was computed could be removed (prune
	/// is an explicit, quiescent-repo operation).
	pub async fn prune_loose(
		&self,
		keep: &HashSet<ObjectId<H>>,
	) -> Result<PruneReport, ObjectStoreError> {
		let mut pruned = 0;
		for id in self.loose_object_ids().await? {
			if !keep.contains(&id) {
				self
					.files
					.delete_path(&loose_object_path(&id), None)
					.await?;
				pruned += 1;
			}
		}
		Ok(PruneReport { pruned })
	}
}

#[cfg(test)]
mod tests {
	use super::geometric_split;

	#[test]
	fn already_geometric_rolls_up_nothing() {
		// Each pack is ≥ 2× the total below it → no batch.
		assert_eq!(geometric_split(&[50, 100, 200], 2), 0);
		assert_eq!(geometric_split(&[1], 2), 0);
		assert_eq!(geometric_split(&[], 2), 0);
	}

	#[test]
	fn rolls_up_the_small_packs_under_a_big_one() {
		// Three small packs and one large: the small ones become the batch, the large is kept.
		assert_eq!(geometric_split(&[1, 1, 1, 100], 2), 3);
		// Two equal small packs under a big one: they roll up together.
		assert_eq!(geometric_split(&[2, 2, 20], 2), 2);
	}

	#[test]
	fn rolls_up_everything_when_no_pack_dominates() {
		// A flat run (no pack is 2× the batch below it) rolls all of them together.
		assert_eq!(geometric_split(&[3, 4, 5, 6], 2), 4);
	}

	#[test]
	fn a_low_factor_is_clamped_and_huge_counts_saturate() {
		// factor < 2 is treated as 2.
		assert_eq!(geometric_split(&[50, 100, 200], 1), 0);
		// A saturating `factor * x` must not panic on near-`u64::MAX` counts (here it reads as
		// already geometric — the point is that it terminates without overflow).
		assert_eq!(geometric_split(&[u64::MAX, u64::MAX], 2), 0);
	}
}
