[package]
description = "Backend storage trait for gitana's Git repositories."
edition.workspace = true
license.workspace = true
name = "gitana-file-store"
repository.workspace = true
rust-version.workspace = true
version.workspace = true
[dependencies]
thiserror.workspace = true
tokio = { workspace = true, features = ["io-util"] }

[lints]
workspace = true
