[package]
edition.workspace = true
license.workspace = true
name = "gitana-file-store-conformance"
repository.workspace = true
rust-version.workspace = true
version = "0.1.0"

[lints]
workspace = true

[dependencies]
gitana-file-store.workspace = true
tokio = { workspace = true, features = ["io-util"] }
